### PR TITLE
Primer3 files

### PR DESCRIPTION
**Pull request by erasche**
Working on a [primer3](http://biotools.umassmed.edu/bioapps/primer3_www.cgi) tool since my users want that.

### CODE REVIEW

**Comment by bgruening** [comment]
Fantastic! Have also a few users here I guess.

**Comment by erasche** [comment]
FYI There's also a JBrowse plugin for designing primers, so hopefully as we move towards that we'll be able to make use of a more convenient one for our users. :)

**Comment by bgruening** [comment]
Really? Wow. Btw. how far are you with JBrowse? I remember you had some build issues?

**Comment by erasche** [comment]
Yes, progress stalled during grant.

- There are build issues with the gigantic dependency tree and perl crap
- Some more features I need to do for v0.4 of JBrowse (mostly related to color parameters and actually displaying those in the output files)
-  I completely rewrote the data exchange mechanism from Yaml intermediary file to XML and I need to get that working again
- Test cases

**Comment by erasche** [comment]
v0.5 will include a bunch of JBrowse plugins you'll be able to check off that you want included :)

**Comment by bgruening** [comment]
Please point me to the build issues and I will have a look.

**Comment by erasche** [comment]
I'm not finding the precise issue :/ There was https://github.com/galaxyproject/tools-iuc/issues/205 which might've been related but ... don't know at this point.

If you have too much time on your hands, just try installing JBrowse from the MTS in docker, it should fail at multiple points. I had updates to the packages on my laptop, but those are out of date and I'm not confident in them. Sorry for the many delays on this...

**Pull request merged**
